version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    command: sh -c "python -m main"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
